### PR TITLE
Re-ordered countries

### PR DESCRIPTION
**Pull request by chris-erxleben**
## **Description**

INSERT A SMALL DESCRIPTION OF WHAT YOU CHANGED HERE

#### **Verify that...**

- [x] Any related demos where added and `npm start` still works
- [x] New demos work in `Safari`, `Chrome` and `Firefox`
- [x] `npm run lint` passes
- [x] `npm test` passes and code coverage is increased
- [x] `npm run compile` still works

##### **Screenshots**

### CODE REVIEW

**Comment by jgodi** [comment]
|File (1)|Change (:white_check_mark: Pass)|
|---|---|

*Please note, individual file changes won't add up to the overall coverage due to number of lines!*

**All new files must be at 80% coverage and old files must NOT decrease in coverage!**

**Comment by jgodi** [comment]
|File (11)|Change (:bangbang: -1.77%)|
|---|---|
|DistributionListPickerResults.ts|:white_check_mark: +81.25%|
|SkillsSpecialtyPickerResults.ts|:white_check_mark: +100%|
|Unless.ts|:white_check_mark: +92%|
|Render.ts|:bangbang: -0.55%|
|OptionsService.ts|:bangbang: +55.56%|
|Security.ts|:white_check_mark: +80%|
|FormUtils.ts|:bangbang: -57.71%|

*Please note, individual file changes won't add up to the overall coverage due to number of lines!*

**All new files must be at 80% coverage and old files must NOT decrease in coverage!**

**Comment by escarre** [comment]
Can you add a sort to the end of getCountries? Reordering it in-line fixes it for now, but we need to add a sort in order to future proof it. US and UK should still be the top two items.

https://github.com/bullhorn/novo-elements/blob/d01ed786365822a193089c0d667baf12bae821f8/src/platform/utils/countries/Countries.ts#L10419

**Comment by chris-erxleben** [comment]
@escarre The sort is happening in country-state-parser. I used that to generate this file. I could add that sorting logic to that function, but if we always use that tool to generate this file, wouldn't it just be a waste of computation to re-sort it every time?

Link to county-state-parser: https://bhsource.bullhorn.com/DEV_WORKSPACE/country-state-parser

**Comment by jgodi** [comment]
@chris-erxleben Good point, I didn't know we had a tool that generated this file. Good to know!

As long as its sorted by country name and states/provinces being subsorted too, with US/UK on top then this is solid.

**Comment by ndickerson** [comment]
@chris-erxleben - Can we put a comment at the top of the Countries.ts that says something like:

```
AUTOGENERATED FILE - DO NOT EDIT
Generated by: https://bhsource.bullhorn.com/DEV_WORKSPACE/country-state-parser
```

**Comment by escarre** [comment]
Awesome. Thanks @chris-erxleben

**Comment by jgodi** [comment]
|File (1)|Change (:white_check_mark: Pass)|
|---|---|

*Please note, individual file changes won't add up to the overall coverage due to number of lines!*

**All new files must be at 80% coverage and old files must NOT decrease in coverage!**

**Pull request merged**
