### PR TITLE
5.0

### PR DESCRIPTION
**Pull request by jgodi**
## **Description**
New novo-value element
novo-value-phone and novo-value-email are the sub-elements
Render pipe

#### **Verify that...**

- [x] Any related demos where added and `npm start` still works
- [x] New demos work in `Safari`, `Chrome` and `Firefox`
- [x] `npm run lint` passes
- [x] `npm test` passes and code coverage is increased
- [x] `npm run compile` still works

##### **Screenshots**

### CODE REVIEW

**Comment by jgodi** [comment]
|File (7)|Change (:bangbang: -0.99%)|
|---|---|
|Render.ts|:bangbang: +9.47%|
|Value.module.ts|:white_check_mark: +100%|
|Value.ts|:white_check_mark: +80%|
|novo-label-service.ts|:bangbang: -4.21%|
|EntityUtils.ts|:bangbang: +40.38%|

*Please note, individual file changes won't add up to the overall coverage due to number of lines!*

**All new files must be at 80% coverage and old files must NOT decrease in coverage!**

**Comment by jgodi** [comment]
|File (0)|Change (:white_check_mark: Pass)|
|---|---|

*Please note, individual file changes won't add up to the overall coverage due to number of lines!*

**All new files must be at 80% coverage and old files must NOT decrease in coverage!**

**Comment by jgodi** [comment]
|File (4)|Change (:white_check_mark: +0.02%)|
|---|---|
|BaseControl.ts|:white_check_mark: +0.13%|
|FormUtils.ts|:white_check_mark: +0.25%|

*Please note, individual file changes won't add up to the overall coverage due to number of lines!*

**All new files must be at 80% coverage and old files must NOT decrease in coverage!**

**Comment by BRS999** [comment]
I'm eager to play around with ng 5 and Novo Elements. Can't wait!

**Pull request closed without merging**
