### PR TITLE
[WIP] feat(form): Adding a Field Interation API

### PR DESCRIPTION
**Pull request by jgodi**
WIP

### CODE REVIEW

**Comment by amrutha-rajiv** [comment]
should we add a prefix to API to make it more specific to novo-elements so that it doesn't clash with globals provided by other JS libraries?

**Comment by jgodi** [comment]
#### Overall Coverage Change: -0.42%
|File|Change|
|---|---|
|index.ts|No Change|
|index.ts|No Change|
|Control.ts|-0.10%|
|FieldInteractionApi.ts|+37.5%|
|ToastService.ts|No Change|

*Please note, individual file changes won't add up to the overall coverage due to number of lines!*

**Comment by jgodi** [comment]
#### Overall Coverage Change: -0.46%
|File|Change|
|---|---|
|index.ts|No Change|
|index.ts|No Change|
|Control.ts|-0.31%|
|FieldInteractionApi.ts|+38.24%|
|ToastService.ts|No Change|

*Please note, individual file changes won't add up to the overall coverage due to number of lines!*

**Comment by jgodi** [comment]
#### Overall Coverage Change: -1.85%
|File|Change|
|---|---|
|index.ts|No Change|
|index.ts|No Change|
|Control.ts|-0.83%|
|ControlConfirmModal.ts|+88.89%|
|FieldInteractionApi.ts|+20.3%|
|Form.ts|No Change|
|NovoFormControl.ts|+1.21%|
|BaseControl.ts|+0.15%|
|BasePickerResults.ts|-0.61%|
|TipWell.ts|No Change|
|ToastService.ts|No Change|
|novo-label-service.ts|+0.26%|
|FormUtils.ts|No Change|

*Please note, individual file changes won't add up to the overall coverage due to number of lines!*

**Pull request merged**
