### PR TITLE
Fix(Render) - Address field Display for mobile

### PR DESCRIPTION
**Pull request by tgadre**
## **Description**

Added support for SecondaryAddress and Billing Address display for Vertical Layout

#### **Verify that...**

- [ ] Any related demos were added and `npm start` and `npm run build` still works
- [ ] New demos work in `Safari`, `Chrome` and `Firefox`
- [ ] `npm run lint` passes
- [ ] `npm test` passes and code coverage is increased
- [ ] `npm run build` still works

#### **Bullhorn Internal Developers**
- [ ] Run `Novo Automation`
- [ ] Run `BBO Automation`

##### **Screenshots**

### CODE REVIEW

**Comment by amrutha-rajiv** [comment]
can the formatting changes be undone please 🙏

**Comment by amrutha-rajiv** [comment]
also, did you mean for this to merge into support/2.x.x?

**Comment by tgadre** [comment]
Sorry changed base for MR and yes i can revert the formatting changes.

**Comment by tgadre** [comment]
formatting fixed as well

**Pull request merged**
