### PR TITLE
style(Modal): Center the icon in the circle

### PR DESCRIPTION
**Pull request by tla-dev**
## **Description**

Center the icon in the circle. Tested on chrome, firefox, safari.

#### **Verify that...**

- [x] Any related demos were added and `npm start` and `npm run build` still works
- [x] New demos work in `Safari`, `Chrome` and `Firefox`
- [x] `npm run lint` passes
- [x] `npm test` passes and code coverage is increased
- [x] `npm run build` still works

#### **Bullhorn Internal Developers**
- [ ] Run `Novo Automation`
- [ ] Run `BBO Automation`

##### **Screenshots**

### CODE REVIEW

**Comment by charlesabarnes** [comment]
Can you post a screenshot?

**Comment by tla-dev** [comment]
image

**Comment by tla-dev** [comment]
image

**Comment by tla-dev** [comment]
image

**Pull request merged**
