### PR TITLE
Update Table.ts

### PR DESCRIPTION
**Pull request by BRS999**
multiple filter fix

## **Description**

Multiple filtering fix.

#### **Verify that...**

- [X] Any related demos where added and `npm start` still works
- [X] New demos work in `Safari`, `Chrome` and `Firefox`
- [X] `npm run lint` passes
- [X] `npm test` passes and code coverage is increased
- [X] `npm run compile` still works

### CODE REVIEW

**Comment by BRS999** [comment]
I believe this breaks date filtering.

**Comment by BRS999** [comment]
So this commit does not break date picker filtering. However, I wasn't able to get it to multi-select on the date filter. Any suggestions?

**Comment by jgodi** [comment]
Sorry, I have been busy with the NG 5+ upgrade! I will take a look at this very soon!

**Comment by BRS999** [comment]
I'll close this for now.

**Pull request closed without merging**
